#!/bin/bash

echo Clearing the dist directory
rm -rf dist
mkdir -p dist/icons


function resequence {
    i=10

    echo Resequencing files...
    pattern='(^'$1'[01234567890 ]*)(.*)'

    # count number of files
    fc=0
    for f in $1*.md;
    do
        let "fc=fc+1"
    done
    echo Number of files: $fc
    # calculate the number of digits needed
    let "fc=fc*10"
    calc="echo (l($fc)/l(10)) + 1"
    digitscount=$($calc | bc -l)
    calc="echo scale=0;$digitscount/1"
    digitscount=$($calc | bc -l)
    echo Digits needed in filename: $digitscount

    for f in $1*.md;
    do
    if [[ "$f" =~ $pattern ]]
    then
        calc="printf %0${digitscount}d $i"
        iformatted=$($calc)
        mv "$f" "$1$iformatted ${BASH_REMATCH[2]}" 2>/dev/null
        let "i=i+10"
    fi
    done
}

cd doc
resequence M
resequence S

################################
# For single page
################################
echo Clearing the tmp directory
cd ..
rm -rf tmp
mkdir -p tmp
cd tmp
cp ../doc/S*.md .
cp ../doc/pandocepub.css .
cp ../doc/pandochtml.css .


stub1a="pandoc --from gfm --standalone --toc --highlight-style pygments"
stub1b=" --metadata-file=../doc/pandoc-meta.yaml --include-in-header=../doc/header-includes.txt "
stub1c="-c pandoc"
stub1=${stub1a}${stub1b}${stub1c}
stub2=".css S*.md --output "

function convert {
    echo Converting to $2...
    rm -f $1.$2
    ${stub1}$2${stub2}$1.$2
    echo Copying to dist directory
    cp $1.$2 ../dist/$1.$2
    cp pandoc$2.css ../dist
}
convert single_tmp html
convert freshfood epub 

# Replace the title
sed -f ../doc/replace_title_script.sed ../dist/single_tmp.html > ../dist/single.html
rm ../dist/single_tmp.html


################################
# For multiple pages
################################

# tmp:
cp ../dist/single.html ../dist/index.html


# Copy in the icons
cp ../doc/icons/* ../dist/icons
cp ../favicon.png ../dist/favicon.ico

echo Setting up the local busybox server
cd ..
pkill -f "busybox httpd -p 4202 -h ./dist"
busybox httpd -p 4202 -h ./dist
echo Site served at http://localhost:4202

