#!/bin/bash

# Starting from a download of the zipped html file from Google docs

echo Clearing the dist directory
rm -rf ./dist
mkdir -p ./dist

# Copy and unzip the html file
fileName1="The Fresh Food Diet.zip"
fileName2=TheFreshFoodDiet.html
unzip ~/Downloads/$fileName1 -d ./dist
rm ~/Downloads/"$fileName1"
mv ./dist/$fileName2 ./dist/index.html


# Copy in the favicon
cp ./favicon.png ./dist

echo Setting up the local busybox server
pkill -f "busybox httpd -p 4204 -h ./dist"
busybox httpd -p 4204 -h ./dist
echo Site served at http://localhost:4204

