#!/bin/bash
# The command to update git and the Github Pages site.
# For the doc (which is the Github Pages site, output to "dist" in the root directory of the project
# (the same directory as this file).
# The Github setting for pages should choose the gh-pages branch.
# npm install -g angular-cli-ghpages


if [ $# -gt 0 ]; then
	message=$*
else
	message="Upload changes."
fi

echo $message

# Build the documentation
# ./1-doc_update
./2-doc_update_google

# Send master files to github
git checkout master
git add *
git commit -a -m "${message}"
git push origin master
# no longer works for non-Angular projects: ngh deploy --cname=freshfood.rocks

# Update github pages
#git checkout gh-pages

#git checkout master


