#!/bin/bash
# The command to build the Hugo project so that it can be served by Github pages.
# The config.toml file should have the publishDir set to the dist directory only:
# publishDir = "dist"
# The Github setting for pages should choose the gh-pages branch.
# npm install -g angular-cli-ghpages


if [ $# -gt 0 ]; then
	message=$*
else
	message="Upload changes."
fi

echo $message

# Create a local copy for nginx to serve
hugo --baseURL "http://localhost:4202" --destination "./dist-local"
#rm -r ~/local/web/fresh-food
#mkdir -p ~/local/web/fresh-food
#cp -r ./dist/*  ~/local/web/fresh-food
# to use:

pkill -f "busybox httpd -p 4202 -h ./dist-local"
busybox httpd -p 4202 -h ./dist-local

# Build for github
hugo --baseURL "https://davidgma.github.io/fresh-food/" --destination "./dist"
git add *
git commit -a -m "${message}"
git push
ngh

