baseURL = "https://davidgma.github.io/fresh-food/"
languageCode = "en-gb"
DefaultContentLanguage = "en"
title = "Fresh Food"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir = true
publishDir = "dist"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

[Languages]
[Languages.en]
title = "The Fresh Food Diet"
weight = 1
languageName = "English"
